version: '2.1'
services:

  kafka:
    image: wurstmeister/kafka
    container_name: 'kafka'
    environment:
      JVM_OPTS: -Xmx1g -Xms1g -XX:MaxPermSize=1024m
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: atlas_android_data:1:1,data_warehouse:1:1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENERS: INSIDE://kafka:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092

    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 9093:9093

  zookeeper:
    container_name: 'zookeeper'
    image: wurstmeister/zookeeper

#  worker:
#    build: .
#    container_name: 'worker'
#    environment:
#      KAFKA_BROKERS: kafka
#      KAFKA_INPUT_TOPIC: atlas_android_data
#      KAFKA_GROUP_ID: "atlas-android-data-processor"
#      KAFKA_LOADER_TOPIC: data_warehouse
#      SNOWFLAKE_ACCOUNT: "ng95977"
#      SNOWFLAKE_USER: "NNGUYEN"
#      SNOWFLAKE_PASSWORD: "Operations!1"
#      SNOWFLAKE_DATABASE: "ENGINEERING_DB"
#      SNOWFLAKE_SCHEMA: "ATLAS_DEV"
#      SNOWFLAKE_WAREHOUSE: "ENGINEERING_WH"
#      SNOWFLAKE_ROLE: "ENGINEERING_ROLE"
